config/routes.rb
Rails.application.routes.draw do
  post 'noko/subscribe'
  post 'noko/unsubscribe'

  get 'leaderboard/users'

  get 'leaderboard/projects'

  root 'leaderboard#users'

end

app/models/concerns/calculation.rb
require 'active_support/concern'

module Calculation
  extend ActiveSupport::Concern

  def minutes_of_week(weeks_ago)
    start_date = (Time.now.beginning_of_week - weeks_ago.week).to_date
    end_date = (Time.now.end_of_week - weeks_ago.week).to_date
    entries.where(date: start_date..end_date).sum(:minutes)
  end
end

app/models/concerns/current_week.rb
require 'active_support/concern'

module CurrentWeek
  extend ActiveSupport::Concern

  included do
    scope :week, lambda { |from, to|
      where(start_date: from, end_date: to).order('total_minutes desc')
    }
  end
end

app/models/concerns/leaderboard_calculation.rb
require 'active_support/concern'

module LeaderboardCalculation
  extend ActiveSupport::Concern

  included do
    def self.calculate
      [1, 0].each do |weeks_ago|
        start_date = Time.now.beginning_of_week.to_date - weeks_ago.weeks
        end_date = Time.now.end_of_week.to_date - weeks_ago.weeks
        model_klass = self.name.gsub("Leaderboard", "").constantize

        model_klass.find_each do |record|
          leaderboard = self.find_or_create_by(
            "#{model_klass.name.downcase}_id" => record.id,
            start_date: start_date,
            end_date: end_date)
          leaderboard.update_column(:total_minutes, record.minutes_of_week(weeks_ago))
        end
      end
    end
  end
end

app/models/concerns/leaderboard_scopes.rb
require 'active_support/concern'

module LeaderboardScopes
  extend ActiveSupport::Concern

  included do
    def self.week(from, to)
      where(start_date: from, end_date: to).order('total_minutes desc')
    end

    def self.with_logged_minutes
      where.not(total_minutes: 0)
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  delegate :email, prefix: "user", to: :user

  MINUTES_PER_HOUR = 60

  scope :today, lambda { where(date: Date.today) }

  scope :for_users_by_email, ->(emails) { joins(:user).where('users.email IN (?)', emails).preload(:user) }

  def length
    hour_value = minutes / MINUTES_PER_HOUR
    minute_value = minutes % MINUTES_PER_HOUR
    [time_label("hour", hour_value), time_label("minute", minute_value)].compact.join(", ")
  end

    private

    def time_label(label, value)
      "#{value} #{label.pluralize(value)}" if value > 0
    end

    def self.delete_older_than(date)
      where('date < ?', date).delete_all
    end
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Calculation

  has_many :entries
end

app/models/project_leaderboard.rb
class ProjectLeaderboard < ActiveRecord::Base
  include LeaderboardScopes
  include LeaderboardCalculation

  belongs_to :project

  def name
    project.name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Calculation

  has_many :entries

  scope :active, -> { where(state: "active") }
  scope :with_missing_hours_notification_enabled, -> { where(missing_hours_notification_enabled: true)}

  def self.send_reminders
    return if Date.today.saturday? || Date.today.sunday? || holiday?

    User.active.each do |user|
      if user.entries.today.count == 0
        Reminder.send_to(user).deliver
      end
    end
  end

  private

  def self.holiday?
    ENV["COUNTRY_CODE"] && Holidays.on(Date.today, ENV["COUNTRY_CODE"]).any?
  end
end

app/models/user_leaderboard.rb
class UserLeaderboard < ActiveRecord::Base
  include LeaderboardScopes
  include LeaderboardCalculation

  belongs_to :user

  def name
    user.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  unless Rails.env.test?
    http_basic_authenticate_with name: ENV["BASIC_AUTH_NAME"], password: ENV["BASIC_AUTH_PASSWORD"]
  end
end

app/controllers/leaderboard_controller.rb
class LeaderboardController < ApplicationController
  def users
    @leaderboards = UserLeaderboard.includes(:user)
      .week(start_date, end_date)
        .with_logged_minutes
    render 'partials/leaderboard_table'
  end

  def projects
    @leaderboards = ProjectLeaderboard.includes(:project)
      .week(start_date, end_date)
        .with_logged_minutes
    render 'partials/leaderboard_table'
  end

  private

    def start_date
      @start_date = Time.now.beginning_of_week.to_date - weeks_ago.weeks
    end

    def end_date
      @end_date = Time.now.end_of_week.to_date - weeks_ago.weeks
    end

    def weeks_ago
      @weeks_ago = (params[:weeks_ago] || 0).to_i
    end
end

app/controllers/noko_controller.rb
class NokoController < ApplicationController
  protect_from_forgery with: :null_session

  def subscribe
    user = User.where(["lower(name) LIKE ?", "%#{params["user_name"].downcase}%"]).first
    response_message = "You are already subscribed to the Noko Reminder :llama-yay:" 

    unless user.missing_hours_notification_enabled
      response_message = "You have been subscribed to a Noko time tracking reminder on Fridays :10_10:"
      slack_id = params["user_id"]
      user.update!(slack_id: slack_id, missing_hours_notification_enabled: true)
    end

    render plain: response_message, status: 200
  end
  
  def unsubscribe
    user = User.where(["lower(name) LIKE ?", "%#{params["user_name"].downcase}%"]).first
    response_message = "Im watching you, Wazowski! always watching. :roz:"

    if user.missing_hours_notification_enabled
      response_message = "You are no longer subscribed to the Noko Reminder :squirrel:" 
      user.update!(missing_hours_notification_enabled: false)
    end

    render plain: response_message, status: 200
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def users_active_class
    current_page?(action: 'users') || current_page?(root_url) ? "active" : ""
  end

  def projects_active_class
    current_page?(action: 'projects') ? "active" : ""
  end
end

app/helpers/leaderboard_helper.rb
module LeaderboardHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pecas, Leaderboards for Noko</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'partials/header' %>
  <div class="wrapper">
    <%= yield %>
  </div>
</body>
</html>

app/views/partials/_header.html.erb
<header>
  <div id="logo">
    <h1>Pecas</h1>
    <h2>Leaderboards for Noko</h2>
  </div>

  <ul class="menu">
    <li role="presentation" class="<%= users_active_class %>">
      <%= link_to 'Team', leaderboard_users_path %>
    </li>
    <li role="presentation" class="<%= projects_active_class %>">
      <%= link_to 'Projects', leaderboard_projects_path %>
    </li>
  </ul>
</header>

app/views/partials/leaderboard_table.html.erb
<div class="board">
  <h1><strong>From:</strong> <%= @start_date %> - <%= @end_date %></h1>

  <div class="board-table">
    <table class="table table-striped">
      <thead>
        <tr class="title">
          <th>Rank</th>
          <th>Name</th>
          <th>Hours</th>
        </tr>
      </thead>
      <% @leaderboards.each_with_index do |leaderboard, i| %>
        <tr class="<%= cycle('info', '') %>">
          <td><%= i + 1 %></td>
          <td><%= leaderboard.name %></td>
          <td>
            <%= number_to_human(
                  (leaderboard.total_minutes.to_f / 60).round(2))
            %>
          </td>
        </tr>
      <% end %>
      <tr class="success">
        <td class="total" colspan=2>Total:</td>
        <td>
          <%= pluralize(
                number_to_human(
                  (@leaderboards.map(&:total_minutes).sum.to_f / 60).round(2)), 'hour') %>
        </td>
      </tr>
    </table>
  </div>
  <nav>
    <ul class="pagination">
      <li class="pull-left">
        <a href="?weeks_ago=<%= @weeks_ago + 1 %>" aria-label="Previous Week">
          <span aria-hidden="true">Previous Week</span>
        </a>
      </li>
      <% unless @weeks_ago <= 0 %>
        <li class="pull-right">
          <a href="?weeks_ago=<%= @weeks_ago - 1 %>" aria-label="Next Week">
            <span aria-hidden="true">Next Week</span>
          </a>
        </li>
      <% end %>
    </ul>
  </nav>
</div>

app/views/reminder/send_to.text.erb
Hello <%= @user.name %>,

you forgot to submit your hours. :(

Please submit your hours here:
<%= @url %>

Best regards,
Your Reminder